# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca6a872f5d59478b60b13906152e9f6a614fb234bf29ea5752697b295f6c44a6f63ac8a83f63231b3ee0a6d2dbc2cedc6770266fd87846acbc737799866ba13c

test:
  secret_key_base: 0adcf4f013354481bbb7bf56cc8a1607da9df44d1f997b2ff47aca2b30c1198bf70fedbad3003fd31536a7027db3b2a832274bc89a87afb8ce81f6e68047984b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
